### ISSUE TITLE
Number of dimensions limit for the input coordinate file

### ISSUE THREAD

**Issue by hjuinj** [moldyn/Clustering#8]
Thank you for developing this nice clustering workflow. 

I am currently playing around with the code. I just want to check that, in the [documentation page](https://moldyn.github.io/Clustering/docFEandNN.html) it is said that the input coordinate file should not exceed 10 dimensions, but I briefly checked the source code and it seems there is not a hard limit on the number of dimensions the program takes in. So is this statement mainly for speed reasons rather than an actual limitation?

**Comment by braniii** [comment]
Hi, glad you like the package. You are correct that there is no hard limit. The only (soft) limitation is for the CUDA implementation: the way we allocate the memory you need a lot of video ram to cope with many dimensions. On my old GPUs it runs out of memory at already 8 dimensions.

The statement is from methodical point of view. We are estimating the density with a fixed sphere of radius ![d_\text{lump}^2 = 4 \langle x^2\rangle](https://latex.codecogs.com/svg.latex?d_\text{lump}^2%20=%204%20\langle%20x^2\rangle). This implies the assumption, that within that sphere the density is constant. Further, it can be easily seen that the radius of the sphere ![d_\text{lump}](https://latex.codecogs.com/svg.latex?d_\text{lump}) increases with an increasing number of dimensions, which leads to an increasing error in the density estimation. So taking more dimensions, the resolution in all dimension suffers.

I hope I could help. Do not hesitate to further ask questions.
