### ISSUE TITLE
Example of coords file 

### ISSUE THREAD

**Issue by toontun** [moldyn/Clustering#9]
Hello, 

Is it possible to have an example of the coords file ? 

This link doesn't work: 

`wget http://www.moldyn.uni-freiburg.de/software/aib9.pca.reduced.bz2`

I use gromacs to compute trajectory. How should I process to use your program ? 

Thank you,
Adam

**Comment by braniii** [comment]
Hello Adam,

I just uploaded again the coordinates, thank you for writing us! We switch to a new website and forgot to include the file. In case you are interested in more complex data, I can recommend you to give HP35 a try. There you still need to reduce the dimensionality. You find them in our repo [HP35-DESRES](https://github.com/moldyn/HP35-DESRES) and in [HP35-Benchmark](https://github.com/moldyn/HP35-Benchmark) you find a script which applies periodical PCA (dPCA+) followed by this clustering routine.

If you have any questions, feel free to open a new issue or simple reopen it.

Best
Daniel
